import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    price: 79.99,
    originalPrice: 129.99,
    rating: 4.8,
    reviewCount: 2341,
    image: "/images/wireless-noise-cancelling-headphones.jpg",
    category: "Electronics",
    sale: true,
    saleLabel: "38% OFF",
    badge: "Best Seller",
  },
  {
    id: 2,
    name: "Minimalist Leather Watch",
    price: 149.99,
    rating: 4.7,
    reviewCount: 876,
    image: "/images/minimalist-leather-watch.jpg",
    category: "Accessories",
    sale: false,
    badge: "New Arrival",
  },
  {
    id: 3,
    name: "Ultra-Slim Laptop Stand",
    price: 39.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviewCount: 1203,
    image: "/images/ultra-slim-laptop-stand.jpg",
    category: "Electronics",
    sale: true,
    saleLabel: "33% OFF",
  },
  {
    id: 4,
    name: "Premium Cotton Hoodie",
    price: 59.99,
    rating: 4.9,
    reviewCount: 3102,
    image: "/images/premium-cotton-hoodie.jpg",
    category: "Clothing",
    sale: false,
    badge: "Top Rated",
  },
  {
    id: 5,
    name: "Portable Bluetooth Speaker",
    price: 49.99,
    originalPrice: 79.99,
    rating: 4.5,
    reviewCount: 987,
    image: "/images/portable-bluetooth-speaker.jpg",
    category: "Electronics",
    sale: true,
    saleLabel: "37% OFF",
  },
  {
    id: 6,
    name: "Yoga Mat Pro",
    price: 34.99,
    rating: 4.7,
    reviewCount: 654,
    image: "/images/yoga-mat-pro.jpg",
    category: "Sports",
    sale: false,
  },
  {
    id: 7,
    name: "Ceramic Pour-Over Coffee Set",
    price: 44.99,
    originalPrice: 64.99,
    rating: 4.8,
    reviewCount: 421,
    image: "/images/ceramic-pour-over-coffee-set.jpg",
    category: "Home",
    sale: true,
    saleLabel: "30% OFF",
    badge: "Staff Pick",
  },
  {
    id: 8,
    name: "Slim Fit Chino Pants",
    price: 49.99,
    rating: 4.4,
    reviewCount: 1567,
    image: "/images/slim-fit-chino-pants.jpg",
    category: "Clothing",
    sale: false,
  },
  {
    id: 9,
    name: "Stainless Steel Water Bottle",
    price: 24.99,
    rating: 4.9,
    reviewCount: 4210,
    image: "/images/stainless-steel-water-bottle.jpg",
    category: "Sports",
    sale: false,
    badge: "Best Seller",
  },
  {
    id: 10,
    name: "Linen Throw Pillow Set",
    price: 29.99,
    originalPrice: 44.99,
    rating: 4.6,
    reviewCount: 312,
    image: "/images/linen-throw-pillow-set.jpg",
    category: "Home",
    sale: true,
    saleLabel: "33% OFF",
  },
  {
    id: 11,
    name: "Leather Card Wallet",
    price: 19.99,
    rating: 4.5,
    reviewCount: 2089,
    image: "/images/leather-card-wallet.jpg",
    category: "Accessories",
    sale: false,
  },
  {
    id: 12,
    name: "Running Shoes Ultralight",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.7,
    reviewCount: 743,
    image: "/images/running-shoes-ultralight.jpg",
    category: "Sports",
    sale: true,
    saleLabel: "25% OFF",
    badge: "New Arrival",
  },
  {
    id: 13,
    name: "Smart LED Desk Lamp",
    price: 54.99,
    rating: 4.6,
    reviewCount: 891,
    image: "/images/smart-led-desk-lamp.jpg",
    category: "Home",
    sale: false,
  },
  {
    id: 14,
    name: "Oversized Graphic Tee",
    price: 29.99,
    rating: 4.3,
    reviewCount: 2341,
    image: "/images/oversized-graphic-tee.jpg",
    category: "Clothing",
    sale: false,
    badge: "Trending",
  },
  {
    id: 15,
    name: "Mechanical Keyboard TKL",
    price: 99.99,
    originalPrice: 139.99,
    rating: 4.8,
    reviewCount: 1102,
    image: "/images/mechanical-keyboard-tkl.jpg",
    category: "Electronics",
    sale: true,
    saleLabel: "28% OFF",
  },
  {
    id: 16,
    name: "Sunglasses Polarized",
    price: 39.99,
    rating: 4.5,
    reviewCount: 567,
    image: "/images/sunglasses-polarized.jpg",
    category: "Accessories",
    sale: false,
    badge: "Summer Pick",
  },
];

export const categories = ["All", "Electronics", "Clothing", "Accessories", "Home", "Sports"] as const;
